ait-aecid/logdata-anomaly-miner

.deepsource.toml, .playbook.yml, .travis.yml
This commit adds a ansible-playbook and a travis.yml to the repository.
Travis will automatically run tests. Note that this travis-configuration
is not production ready and a work in progress.
=> Added initial travis-ci

aecid-testsuite/demo/AMiner/aminerDemo.sh, aecid-testsuite/demo/AMiner/demo-config.py, aecid-testsuite/demo/AMiner/jsonConverterHandler-demo-config.py, aecid-testsuite/unit/AnalysisComponentsPerformanceTest.py, aecid-testsuite/unit/analysis/NewMatchIdValueComboDetectorTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchIdValueComboDetector.py
added Unittests
added AMiner Demo
added AnalysisComponentsPerformanceTests
changed the outputs and fixed error in whitelist_event in NewMatchIdValueComboDetector
=> Implemented Tests for the NewMatchIdValueComboDetector

.gitignore, playbook.retry, source/root/usr/lib/logdata-anomaly-miner/aminer/AMinerConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/util/PersistencyUtil.py, source/root/usr/lib/logdata-anomaly-miner/aminer/util/SecureOSFunctions.py, source/root/usr/lib/logdata-anomaly-miner/aminer/ymlconfig.py
Deepsource: exceptions for global-statement
Deepsource: exceptions for imports
Deepsource: fixed unused importlib-import
=> DeepSource: fixed styles in ymlconfig

debian/AMiner.1.xml, source/root/usr/lib/logdata-anomaly-miner/AMiner
This commit adds a "help-screen" with colorful ascii-art
Closes #90
=> Added help-screen

aecid-testsuite/unit/analysis/MissingMatchPathValueDetectorTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/MissingMatchPathValueDetector.py
fixed string v.s. bytearray problem in get_channel_key() of MissingMatchPathValueDetector
=> Fix missing match path value detector

.github/PULL_REQUEST_TEMPLATE
This PR introduces a PR-Template with checkboxes to make it easier to review
Fixes #215
=> added a pr-template

source/root/usr/lib/logdata-anomaly-miner/aminer/schema.py, source/root/usr/lib/logdata-anomaly-miner/aminer/ymlconfig.py
=> added kafkaeventhandler to yaml-config

changelog, debian/copyright, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventCorrelationDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventTypeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/MatchFilter.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/events/EventInterfaces.py, source/root/usr/lib/logdata-anomaly-miner/aminer/input/InputInterfaces.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/ModelElementInterface.py, source/root/usr/lib/logdata-anomaly-miner/aminer/util/History.py, source/root/usr/lib/logdata-anomaly-miner/aminer/util/StringUtil.py, source/root/usr/lib/logdata-anomaly-miner/aminer/util/TimeTriggeredComponentInterface.py, source/root/usr/share/doc/logdata-anomaly-miner/aminer/Changelog.txt
This commit adds Georg Hoeld as author, adds some copyright-disclaimer to the source-files
and adds new changelogs
=> Changes for new release 2.1.0

Dockerfile, scripts/aminerwrapper.sh
This commit adds a Dockerfile and a wrapper-script that starts the
logdata-anomaly-miner or it's remote-control inside the
docker-container.
- Added a Dockerfile
- Added a wrapper-script for docker-containers
closes #238
=> Added a Dockerfile

aecid-testsuite/demo/AMiner/demo-config.py, aecid-testsuite/demo/AMiner/demo-config.yml, aecid-testsuite/demo/AMiner/jsonConverterHandler-demo-config.py, aecid-testsuite/demo/AMinerRemoteControl/demo-config.py, aecid-testsuite/unit/AnalysisComponentsPerformanceTest.py, aecid-testsuite/unit/analysis/ParserCountTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/ParserCount.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schema.py, source/root/usr/lib/logdata-anomaly-miner/aminer/ymlconfig.py
=> Refactor Count Report

.travis.yml
=> Template config test

source/root/usr/lib/logdata-anomaly-miner/aminer.py
=> Default config yml

source/root/usr/lib/logdata-anomaly-miner/aminer/ymlconfig.py
=> Refactor ymlconfig build analysis pipeline

source/root/etc/aminer/conf-available/ait-lds/SuricataFastParsingModel.py
=> Fix Typo in SuricataFastParsingModel

source/root/usr/lib/logdata-anomaly-miner/aminer.py
- ignores import warnings in code.
-
-
Fixes #218
=> Ignore import warnings

.github/pull_request_template.md
=> Change PR Template

requirements.txt
=> Requirements File

.travis.yml, aecid-testsuite/integration/declarations.sh, aecid-testsuite/unit/config/config.py, aecid-testsuite/unit/events/DefaultMailNotificationEventHandlerTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/events/DefaultMailNotificationEventHandler.py
- implements the DefaultMailNotificationHandler without using subprocesses.
-
-
Fixes #49
=> Reimplement default mail handler

source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/YamlSchema.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventCorrelationDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py
Development
Fixes #301
- Renames allowlist to constraint_list
- Renames blocklist to ignore_list
- leaves allowlist_event as is.
=> Create ignore_list and constraint_list for parser tree paths

debian/aminer.1.xml, debian/aminerremotecontrol.1.xml, scripts/create_aminerremotecontrol_wiki.sh, source/root/usr/lib/logdata-anomaly-miner/aminer.py, source/root/usr/lib/logdata-anomaly-miner/aminer/AMinerRemoteControlExecutionMethods.py, source/root/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py
Fixes #297
Fixes #311 
- updates man pages
- new wiki page was sent via mail.
- new config properties can be changed via remote control.
=> Update man pages

aecid-testsuite/Dockerfile, scripts/testingwrapper.sh
- Updated the Dockerfile so that it uses Debian Bullseye as base-image
- Created a Dockerfile for the aecid-testsuite
fixes #220
=> Feature dockerfile

Jenkinsfile, aecid-testsuite/runSuspendModeTest.sh
=> added Jenkinsfile

Jenkinsfile, aecid-testsuite/Dockerfile
- Fixed problems with paralell jenkins-builds
- Added pythonacl to dockerfile for testing
=> fixed errors with testing-dockerfile and paralell jenkins-builds

Jenkinsfile
- parallel tests for demo-configs
- coverage should run only in development-branch
=> Jenkins: parallel-tests for demo-tests

Jenkinsfile, aecid-testsuite/Dockerfile, scripts/testingwrapper.sh
This commit adds capabilities to run tests for remoteControlTests, TryItOut and GettingStartet
with the Dockercontainer.
- [] I added related issues using the "Fixes #123'-notations
- adds remoteControlTest to the testwrapper of the Dockerfile
- adds TryItOutTest to the testwrapper of the Dockerfile
- adds GettingStartetTest to the testwrapper of the Dockerfile
- adds those tests to the jenkinsfile(but disabled with comments)
=> Enhanced Testing: remoteControlTests, TryItOut and GettingStartet

scripts/aminerwrapper.sh
Development
Fixes #364
- adds the persistence tool to the aminerwrapper.
-
-
=> Add persistence tool

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py
Fixes #342 
- The number of saved values in the ETD is now increased, if the parameters of the VTD requires it
=> VTD_check_num_with_ETD

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableCorrelationDetector.py
Fixes #369
- Added warnings in the VCD to warn if parameters in the ETD had to be increased to prevent an error in the VCD
=> VTD warning if parameters have to be changed in the ETD

Jenkinsfile, aecid-testsuite/docker/Dockerfile_deb, scripts/distritest.sh
fixes #220 
- add a dockerfile for debian and ubuntu
- add a testscript (docker-wrapper)
- add tests to jenkinsfile
=> Deb dockerfiles

changelog, debian/changelog, source/root/usr/share/doc/logdata-anomaly-miner/aminer/Changelog.txt
- [] I added related issues using the "Fixes #123'-notations
- Added changelog for version 2.2.0
=> Added Changelog for version 2.2.0

README.md
=> Fix build-status

source/root/usr/lib/logdata-anomaly-miner/aminer-persistence.py
Fixes #377 
- Adds the missing hashbang
=> Add hashbang to aminer-persistence.py (fixes #377)

debian/changelog, debian/control, debian/logdata-anomaly-miner.links, debian/logdata-anomaly-miner.maintscript, debian/patches/0001-Add-hashbang.patch, debian/patches/series, debian/rules, source/root/usr/lib/logdata-anomaly-miner/aminer-persistence.py
Fixes #379 
- debian/control:
- Bump Standards-Version
- Set RRR: no
- debian/logdata-anomaly-miner.maintscript: Move conffiles to new location
- debian/logdata-anomaly-miner.links: Add link for aminer-peristence.py
- debian/patches: Add hashbang to aminer-peristence.py
- debian/rules:
- Simplify rules by using execute_before_dh_auto_build target
- Remove executable bits of some Python modules
=> Update Debian packaging for 2.2.0

source/root/usr/lib/logdata-anomaly-miner/metadata.py
Fixes #
- updated the version number in metadata.py
=> Modified version number

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py
Fixes #307 
-Refactoring of the VTD-output, when VTs change
=> Refactoring of the VTD-output

aecid-testsuite/unit/analysis/EventFrequencyDetectorTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/YamlSchema.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventFrequencyDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/__init__.py
Fixes #399
- Add an analsis component that detects deviations in occurrence frequencies
=> Add frequency detector

aecid-testsuite/Dockerfile, changelog, debian/changelog, source/root/usr/lib/logdata-anomaly-miner/metadata.py
- Updated the changelog
- Added Version-String 2.2.1
=> added changes to changelog and modified version-string

aecid-testsuite/unit/analysis/EventFrequencyDetectorTest.py, aecid-testsuite/unit/analysis/EventSequenceDetectorTest.py
Fixes #412 
- Improve documentation of tests for ESD, EFD
=> Improve test documentation

aecid-testsuite/runUnittests.sh
Fixes #
- updates an old kafka download link.
=> updated kafka download link.

aecid-testsuite/runUnittests.sh, aecid-testsuite/unit/TestBase.py, aecid-testsuite/unit/analysis/EventFrequencyDetectorTest.py, aecid-testsuite/unit/analysis/EventSequenceDetectorTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/AMinerRemoteControlExecutionMethods.py, source/root/usr/lib/logdata-anomaly-miner/aminer/ConfigValidator.py, source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EnhancedNewMatchPathValueComboDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventCorrelationDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventTypeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/HistogramAnalysis.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/MissingMatchPathValueDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableCorrelationDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/events/EventData.py, source/root/usr/lib/logdata-anomaly-miner/aminer/input/LogStream.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/DateTimeModelElement.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/DecimalFloatValueModelElement.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/DecimalIntegerValueModelElement.py, source/root/usr/lib/logdata-anomaly-miner/aminer/util/PersistenceUtil.py
Fixes #421
- Fixes deepsource issues
=> Fix deepsource issues

aecid-testsuite/runCoverageTests.sh
- fixed kafka-version in coverage-tests
=> fixed kafka-version in coverage-tests

Jenkinsfile
Due to problems with kafka, the coverage-tests were temporarily
disabled.
- disabled coverage test
=> Disabled Coverage-Test

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableCorrelationDetector.py
Fixes #433 
- Fixed the warning in the VCD
=> Fixed the warning in the VCD

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py
Fixes #434 
- Fixed the warning in the VTD
=> Fixed the warning in the VTD

aecid-testsuite/unit/analysis/VariableCorrelationDetectorTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableCorrelationDetector.py
Fixes #432 
- Fixed the method pick_cor_match_disc_vals
=> Fixed VCD method match_disc_vals

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableCorrelationDetector.py
Fixes #442 
- Added a query in the VCD to check if the ETD skipped the currently processed line (because it doesn't have a path in the constraint list)
=> Query in the VCD to check if ETD has skipped the current line

aecid-testsuite/runUnittests.sh
=> remove kafka-client.conf

Jenkinsfile, aecid-testsuite/runGettingStarted.sh, aecid-testsuite/runTryItOut.sh
- This commit fixes wiki-tests in the main-branch by removing the hardcoded "development"-branch in the Test-Scripts
=> make wiki-tests branch-dependent

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableCorrelationDetector.py
Fixes #406 
- Changed the variable w_rel_bt_results into w_rel_ht_results
=> Renamed a variable in the VCD

aecid-testsuite/runUnittests.sh, aecid-testsuite/unit/TestBase.py, aecid-testsuite/unit/util/PersistenceUtilTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventCorrelationDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventFrequencyDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventSequenceDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventTypeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/HistogramAnalysis.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/MatchValueAverageChangeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/MissingMatchPathValueDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchPathDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchPathValueDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/TimeCorrelationDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/TimeCorrelationViolationDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableCorrelationDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/util/PersistenceUtil.py
Fixes #398
- adds a warning if the same persistence file is used multiple times.
=> 008 warning persist file

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchIdValueComboDetector.py
Fixes #538 
- There was a break statement that prevented that multiple paths could be learned for the same id_path
=> Fix allow multiple values per id path

aecid-testsuite/unit/parsing/JsonModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py
=> added null value handling in JsonModelElement.

aecid-testsuite/unit/analysis/EventFrequencyDetectorTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventFrequencyDetector.py
Fixes #584 
- Add floor and ceil to limits in EFD check
=> Add floor and ceil in EFD check

aecid-testsuite/runHowToCreateYourOwnFrequencyDetector.sh, aecid-testsuite/runHowToCreateYourOwnSequenceDetector.sh
=> HOTFIX DEVELOPMENT

source/root/etc/aminer/conf-available/ait-lds/SyslogParsingModel.py
Fixes #521 
- Fix unparsed leap day in syslog parsing model
=> Fix unparsed leap day in syslog parsing model

changelog, debian/changelog, requirements.txt, source/root/usr/lib/logdata-anomaly-miner/metadata.py
=> Release 2.3.0

aecid-testsuite/unit/analysis/EventCorrelationDetectorTest.py, aecid-testsuite/unit/analysis/VariableCorrelationDetectorTest.py, aecid-testsuite/unit/analysis/VariableTypeDetectorTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/ConfigValidator.py, source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventTypeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/HistogramAnalysis.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/TimeCorrelationDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/TimeCorrelationViolationDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableCorrelationDetector.py
=> fixed deepsource issues.

source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py
Fixes #603 
- changed the calculation of indices when the match element is None.
=> fixed match_context updates to be more precise.

aecid-testsuite/Dockerfile, aecid-testsuite/unit/TestBase.py, aecid-testsuite/unit/parsing/AnyByteDataModelElementTest.py, aecid-testsuite/unit/parsing/Base64StringModelElementTest.py, aecid-testsuite/unit/parsing/DateTimeModelElementTest.py, aecid-testsuite/unit/parsing/FixedDataModelElementTest.py, aecid-testsuite/unit/parsing/MultiLocaleDateTimeModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/input/JsonStateMachine.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/Base64StringModelElement.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/DateTimeModelElement.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/DecimalFloatValueModelElement.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/DecimalIntegerValueModelElement.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/FixedWordlistDataModelElement.py
updated unittests for FixedDataModelElement.
Fixes #577 
Fixes #587 
- added comparison methods to TestBase.
- added None and empty list cases to input validation
- updated unittests for FixedDataModelElement, AnyByteDataModelElement, Base64StringModelElement, DateTimeModelElement, MultiLocaleDTME
- replaced all ' with " as default string and bytestring specifier (only already changed classes).
- added source for JsonStateMachine
- renamed all parser id's to element_id.
- updated comments in MultiLocaleDTME
=> Fix rewritten unittests.

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/ParserCount.py
Fixes #588 
- fixed resetting the CurrentProcessedLines in ParserCount.
=> fixed resetting CurrentProcessedLines in ParserCount.

aecid-testsuite/unit/TestBase.py
Fixes #604 
- changed user "aminer" to the default user in unittest logging.
=> changed test logging user.

scripts/testingwrapper.sh
=> HOTFIX - ACCEPT ASAP: added runAminerEncodingDemo to testingwrapper.

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EnhancedNewMatchPathValueComboDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventCorrelationDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventFrequencyDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventSequenceDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/MissingMatchPathValueDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchIdValueComboDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchPathDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchPathValueComboDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchPathValueDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/Rules.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/input/InputInterfaces.py
=> fixed import errors with STAT_LEVEL.

aecid-testsuite/unit/parsing/DecimalFloatValueModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/DecimalFloatValueModelElement.py
=> undid changes in DecimalFloat.

aecid-testsuite/unit/events/JsonConverterHandlerTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/events/JsonConverterHandler.py
Fixes #629 
- this error actually was no error, but was always printed. Now no error is written any more.
=> removed JsonError.

aecid-testsuite/unit/data/YamlConfigTest.py, aecid-testsuite/unit/data/configfiles/unknown_analysis_component.yml, aecid-testsuite/unit/data/configfiles/unknown_parser_config.yml, source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
=> fixed error messages on unknown components.

Jenkinsfile, aecid-testsuite/Dockerfile, aecid-testsuite/runMypy.sh, aecid-testsuite/unit/parsing/AnyByteDataModelElementTest.py, aecid-testsuite/unit/parsing/Base64StringModelElementTest.py, aecid-testsuite/unit/parsing/DateTimeModelElementTest.py, aecid-testsuite/unit/parsing/DebugModelElementTest.py, aecid-testsuite/unit/parsing/DecimalFloatValueModelElementTest.py, aecid-testsuite/unit/parsing/FixedDataModelElementTest.py, scripts/testingwrapper.sh
Fixes #
- mypy errors
- added bool input validation
=> 084 hotfix + bool input validation

aecid-testsuite/Dockerfile, aecid-testsuite/runMypy.sh
=> fixed mypy tests.

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/ParserCount.py
=> fixed current count in ParserCount.

aecid-testsuite/unit/TestBase.py, aecid-testsuite/unit/parsing/AnyByteDataModelElementTest.py, aecid-testsuite/unit/parsing/Base64StringModelElementTest.py, aecid-testsuite/unit/parsing/DateTimeModelElementTest.py, aecid-testsuite/unit/parsing/DebugModelElementTest.py, aecid-testsuite/unit/parsing/DecimalFloatValueModelElementTest.py, aecid-testsuite/unit/parsing/ElementValueBranchModelElementTest.py, aecid-testsuite/unit/parsing/FixedDataModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/ElementValueBranchModelElement.py
=> 086 rewrite element value branch me

source/root/usr/lib/logdata-anomaly-miner/aminer.py
Fixes #607 
- added try/except if POSIX ACLs do not exist.
=> fixed error when POSIX ACLs do not exist.

aecid-testsuite/unit/parsing/DelimitedDataModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/DelimitedDataModelElement.py
=> rewrote unittests for the DelimitedDataModelElement.

aecid-testsuite/unit/analysis/RulesTest.py, aecid-testsuite/unit/parsing/MatchContextTest.py, aecid-testsuite/unit/parsing/VariableByteDataModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/MatchContext.py
=> 094 create unittests for MatchContext and DebugMatchContext

aecid-testsuite/runHowToCreateYourOwnFrequencyDetector.sh, aecid-testsuite/runHowToCreateYourOwnSequenceDetector.sh, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py
=> HOTFIX WIKI TESTS

aecid-testsuite/unit/parsing/AnyByteDataModelElementTest.py, aecid-testsuite/unit/parsing/WhiteSpaceLimitedDataModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/WhiteSpaceLimitedDataModelElement.py
=> rewrote unittests for the WhiteSpaceLimitedDataModelElement.

aecid-testsuite/unit/parsing/ParserMatchTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/ParserMatch.py
=> rewrote unittests for ParserMatch.

aecid-testsuite/unit/parsing/IpAddressDataModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/IpAddressDataModelElement.py
Fixes #652 
Fixes #662
Fixes #664 
-
=> rewrote unittests for the IpAddressDataModelElement.

aecid-testsuite/unit/parsing/HexStringModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/HexStringModelElement.py
=> 090 rewrite hex me

aecid-testsuite/integration/aminerIntegrationTest2.sh, aecid-testsuite/runHowToCreateYourOwnFrequencyDetector.sh, aecid-testsuite/runHowToCreateYourOwnSequenceDetector.sh
Fixes #
- wrong path in integration test was fixed.
=> FIX DEVELOPMENT

aecid-testsuite/unit/parsing/FixedWordlistDataModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/FixedWordlistDataModelElement.py
=> rewrote unittests for the FixedWordlistDataModelElement.

aecid-testsuite/runUnittests.sh
=> fix kafka download link.

aecid-testsuite/integration/aminerIntegrationTest2.sh, aecid-testsuite/unit/parsing/JsonModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py
=> fixed error in JsonModelElement.

aecid-testsuite/unit/parsing/AnyByteDataModelElementTest.py, aecid-testsuite/unit/parsing/Base64StringModelElementTest.py, aecid-testsuite/unit/parsing/DateTimeModelElementTest.py, aecid-testsuite/unit/parsing/DebugModelElementTest.py, aecid-testsuite/unit/parsing/DecimalFloatValueModelElementTest.py, aecid-testsuite/unit/parsing/DecimalIntegerValueModelElementTest.py, aecid-testsuite/unit/parsing/DelimitedDataModelElementTest.py, aecid-testsuite/unit/parsing/ElementValueBranchModelElementTest.py, aecid-testsuite/unit/parsing/FirstMatchModelElementTest.py, aecid-testsuite/unit/parsing/FixedDataModelElementTest.py, aecid-testsuite/unit/parsing/FixedWordlistDataModelElementTest.py, aecid-testsuite/unit/parsing/HexStringModelElementTest.py, aecid-testsuite/unit/parsing/IpAddressDataModelElementTest.py, aecid-testsuite/unit/parsing/JsonModelElementTest.py, aecid-testsuite/unit/parsing/MultiLocaleDateTimeModelElementTest.py, aecid-testsuite/unit/parsing/OptionalMatchModelElementTest.py, aecid-testsuite/unit/parsing/RepeatedElementDataModelElementTest.py, aecid-testsuite/unit/parsing/SequenceModelElementTest.py, aecid-testsuite/unit/parsing/VariableByteDataModelElementTest.py, aecid-testsuite/unit/parsing/WhiteSpaceLimitedDataModelElementTest.py
Fixes #669 
- refactored input validation to be one liners
- moved imports to the top of the file
=> 105 refactor unittests

source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/TSAArimaDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/AnalysisNormalisationSchema.yml, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
Fixes #682
-Added a threshold for the ACF in the TSA
=> Add TSA ACF-threshold

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py
Fixes #687 
- Improved the output of the Initialization of variable types.
=> VTD: Improved initalization message

source/root/usr/lib/logdata-anomaly-miner/aminer.py
Fixes #697 
- changed input parameters to be strings and converted in the program itself to solve the issue.
=> fixed stat and debug parameters.

aecid-testsuite/unit/data/configfiles/same_id_analysis.yml, aecid-testsuite/unit/data/configfiles/same_id_event_handlers.yml, aecid-testsuite/unit/data/configfiles/same_id_parser.yml, aecid-testsuite/unit/data/configfiles/suppress_config.yml, aecid-testsuite/unit/data/configfiles/template_config.yml, source/root/etc/aminer/template_config.yml, source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
Fixes #698 
- all parsers now can be the start point.
=> fixed start error.

Jenkinsfile, scripts/deploydocs.sh
- [] Issues exist for this PR
- [] I added related issues using the "Fixes #<issue-id>"-notations
- added a deployment-script for deploying the documentation
- added documentation-build to the Jenkins-pipeline
=> Jenkinsfile: building docs into a temporary directory

Jenkinsfile
- [] I added related issues using the "Fixes #<issue-id>"-notations
- Changed static branchname for deploying the docs by using a jenkins-variable
=> fixed branchname in Jenkinsfile for deploying the docs

.gitignore, docs/CONFIGURATION.rst
- added command-line parameters to documentation
- added _build-directory to .gitignore (for mkdocs using docker)
=> added command-line parameters to documentation

scripts/aminer_install.sh
It is now possible to set the git-branch via cli-parameters for the install.sh
Fixes #715
- Improved cli-parameters for install.sh
=> Improved command line options for install script

docs/CONFIGURATION.rst
- [] Issues exist for this PR
- [] I added related issues using the "Fixes #<issue-id>"-notations
Fixes #
- Add analysis components documentation
=> Add analysis components to documentation

aecid-testsuite/unit/parsing/JsonModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py
Fixes #740 
- added code to check if the json text is ascii. If yes, it is decoded as unicode-escape. In the other case it is utf-8.
=> 110 fix json encoding with umlauts

docs/CONFIGURATION.rst, requirements.txt, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/HistogramAnalysis.py
- Add documentation for many analysis-components
=> Docs histo

AUTHORS, changelog, debian/changelog, debian/copyright, source/root/usr/lib/logdata-anomaly-miner/metadata.py
- Prepared Aminer for release 2.4.0
=> Release 2.4.0

source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py
Fixes #747 
- Fixed handling of empty sets in JsonModelElement
=> Fixed handling of empty sets in JsonModelElement

aecid-testsuite/unit/parsing/JsonModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py
=> 111 fixed handling of json objects.

Jenkinsfile, docs/CONFIGURATION.rst
=> Fix ci and docs

source/root/lib/systemd/system/aminer.service, source/root/usr/lib/logdata-anomaly-miner/metadata.py
Fixes systemd-script
- Added development-version-string
- Modified path to touch and chown in systemd-script
=> Fix systemd script

aecid-testsuite/unit/parsing/JsonModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py
=> added unittest for EMPTY_LIST and EMPTY_OBJECT.

aecid-testsuite/unit/parsing/JsonModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py
=> 120 fixed error with \x encoded json data.

source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py
=> 122 added code to allow empty objects with optional data.

aecid-testsuite/unit/parsing/DateTimeModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/DateTimeModelElement.py
=> 124 timezone format

aecid-testsuite/unit/parsing/JsonModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py
=> 128 added EMPTY_STRING option to the JsonModelElement.

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/TSAArimaDetector.py
=> Fixed the falsely merged variable name

Jenkinsfile
Fixes #615
- added tests for production dockerfile
=> added simple tests for docker production images

Jenkinsfile, aecid-testsuite/runConfAvailableTest.sh, scripts/testingwrapper.sh
=> 130 added testingwrapper.

aecid-testsuite/runConfAvailableTest.sh
=> fixed error.

aecid-testsuite/demo/aminer/demo-config.py, aecid-testsuite/demo/aminer/demo-config.yml, aecid-testsuite/demo/aminer/jsonConverterHandler-demo-config.py
=> 136 added slashes to some paths in the demo configs.

Jenkinsfile, aecid-testsuite/runGettingStarted.sh, aecid-testsuite/runHowToCreateYourOwnSequenceDetector.sh
=> 135 fix getting started

aecid-testsuite/unit/events/JsonConverterHandlerTest.py, aecid-testsuite/unit/events/KafkaEventHandlerTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/events/EventData.py, source/root/usr/lib/logdata-anomaly-miner/aminer/events/JsonConverterHandler.py
=> 133 Changed output of the JsonConverterHandler to be valid json data.

aecid-testsuite/demo/aminerJsonInputDemo/windows.yml, aecid-testsuite/runConfAvailableTest.sh, aecid-testsuite/runJsonDemo.sh, aecid-testsuite/unit/parsing/JsonModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py
Fixes #870
- added possiblity to parse arrays of arrays (more than 2)
- renamed EMPTY_LIST to EMPTY_ARRAY
=> 139 added possiblity to parse array of arrays.

source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
=> renamed EMPTY_LIST to EMPTY_ARRAY

changelog, debian/changelog, source/root/usr/lib/logdata-anomaly-miner/metadata.py
This commit updates changelog, debian/changelog and metadata for release
2.4.1
Fixes #
-
=> Release 2.4.1

aecid-testsuite/unit/parsing/JsonModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py
=> 142 objects are parsed, when there should be an array.

source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventTypeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/TSAArimaDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/AnalysisNormalisationSchema.yml, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
=> Tsa force period length

source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
=> TSA: Fix problem with variable learn_mode

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventTypeDetector.py
=> ETD: Remove persisting of the following modules

source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/TSAArimaDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/AnalysisNormalisationSchema.yml, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
=> TSA: Added minimal average number of log lines per time step

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventTypeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/TSAArimaDetector.py
=> Refactored the output of the calculation of the time steps

docs/CONFIGURATION.rst, source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/AnalysisNormalisationSchema.yml, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
=> VTD: Changed the parameter update_var_type_bool to learn_mode

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py
=> VTD: Added a test if values are stored in the ETD

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py
=> VTD: Fixed a bug related to the persistency

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventTypeDetector.py
=> ETD: Slimed the persistency down

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/PathArimaDetector.py
=> Fixed the bug, where the affected paths were set to None

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py
=> VTD: Fixed bug when ETD used id_paths and VTD saved statistics

aecid-testsuite/unit/analysis/ValueRangeDetectorTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/ValueRangeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/util/JsonUtil.py
=> fixed persistence handling for ValueRangeDetector.

aecid-testsuite/runAminerJsonInputDemo.sh, aecid-testsuite/unit/parsing/JsonModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py
Fixes #891 
Fixes #947 
Fixes #925
- fixed error with allow_all_keys
- changed ALLOW_ALL to allow all data types
- changed the JsonModelElement to allow the usage of dictionaries in lists.
=> 144 fix json model element

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/PathArimaDetector.py
=> PAD: Extended reinitialisation of the arima model

aecid-testsuite/unit/parsing/DateTimeModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/DateTimeModelElement.py
Fixes #974 
- extended unittests
- fixed performance issues of %z
old implementation performance:
```
Every date is run 100000 times.
No %z parameter ([18/Oct/2021:16:12:55):  5.5703608019994135
Date with %z parameter (18/Oct/2021:16:12:55 UTC+0100):  83.63453283799936
Date with %z parameter (18/Oct/2021:16:12:55 +0000):  70.19066965300044
```
new implementation performance:
```
Every date is run 100000 times.
No %z parameter ([18/Oct/2021:16:12:55):  2.82154846100093
Date with %z parameter (18/Oct/2021:16:12:55 UTC+0100):  3.4400873569975374
Date with %z parameter (18/Oct/2021:16:12:55 +0000):  3.3153898140008096
```
=> Fixed %z performance issues.

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/MinimalTransitionTimeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/PathValueTimeIntervalDetector.py
=> Enhanced output of MTTD and PVTID

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py
=> VTD: Fixed a bug (static -> discrete)

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/PathValueTimeIntervalDetector.py
=> PVTID: Added check if atom time is None

docs/CONFIGURATION.rst, source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/PathValueTimeIntervalDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/AnalysisNormalisationSchema.yml, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
=> PVTID: Renamed parameter time_window_length to time_period_length

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py
=> VTD: Added check for CM homogeneity test

source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableCorrelationDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
=> VCD: Added parameter learn_mode

source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableCorrelationDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
=> VCD: Added parameter paths

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventSequenceDetector.py
=> fixed issues with ESD.

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/PathValueTimeIntervalDetector.py
=> PVTID: Fixed output format of previously appeared times

aecid-testsuite/demo/aminerRemoteControl/aminerRemoteControlDemo.sh, aecid-testsuite/demo/aminerRemoteControl/demo-config.py, aecid-testsuite/runRemoteControlTest.sh, debian/aminerremotecontrol.1.xml, source/root/usr/lib/logdata-anomaly-miner/aminer/AminerRemoteControlExecutionMethods.py, source/root/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py
=> Added rotation method for StreamPrinterEventHandler streams.

Jenkinsfile, changelog, debian/changelog, docs/conf.py, source/root/usr/lib/logdata-anomaly-miner/metadata.py
=> Version 2.5.0

debian/changelog, debian/control, debian/rules
Changes from the upload of 2.5.0-1 to the Debian archive
=> Debian 2.5.0-1

docs/CONFIGURATION.rst, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/PathArimaDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/AnalysisNormalisationSchema.yml
=> PAD: Use binom_test as test if model should be reinitialized

docs/CONFIGURATION.rst, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
Fixes #1004
- VTD: Changed the value of parameter num_updates_until_var_reduction to track all variables from False to 0.
=> VTD: Enhance parameter to test all variables

Jenkinsfile, aecid-testsuite/runReleaseStringCheck.sh, aecid-testsuite/testFunctions.sh, scripts/testingwrapper.sh
Fixes #824 
- Update the version string by running `sudo bash runReleaseStringCheck.sh -u`
=> added version string check.

source/root/etc/aminer/conf-available/ait-lds2/EximParsingModel.py, source/root/etc/aminer/conf-available/ait-lds2/SyslogParsingModel.py
Fixes #
- Add parser models for AIT-LDSv2
=> Add new parser models

docs/CONFIGURATION.rst, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/DateTimeModelElement.py
Fixes #1042 
Fixes #892 
Fixes #893 
- added documentation of missing settings.
=> Documentation

Jenkinsfile
=> parallelized Jenkinsfile.

Jenkinsfile
=> fixed error in jenkinsfile.

Jenkinsfile
=> FIX Jenkinsfile

aecid-testsuite/unit/analysis/EventFrequencyDetectorTest.py, docs/CONFIGURATION.rst, source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventFrequencyDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/AnalysisNormalisationSchema.yml, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
=> EFD: Added option to set the lower and upper limit of the range interval

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/CharsetDetector.py
=> Fix incorrect message of charset detector

source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/DecimalFloatValueModelElement.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/DecimalIntegerValueModelElement.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/VariableByteDataModelElement.py
Fixes #248
- Replace lists with sets for faster lookup
=> Improve performance

scripts/supervisord.conf
The include block allows to add config-files to the directory
/etc/supervisor/conf.d/*.conf.
- this commit allows to configure supervisord via files in config-directory
=> Added include-directive to supervisord.conf

aecid-testsuite/unit/parsing/JsonModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py
=> 165 fixed JsonModelElement when json object is null.

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/MinimalTransitionTimeDetector.py
=> MTTD: fixed minor bug

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/ParserCount.py
=> ParserCounter: Fixed do_timer

source/root/usr/lib/logdata-anomaly-miner/metadata.py
Fixes #1023 
Following outputs are produced based on the version string:
```
(Austrian Institute of Technology)
(https://aecid.ait.ac.at)
Version: 2.5.0  
```          
```
(Austrian Institute of Technology)
(https://aecid.ait.ac.at)
Version: 2.5.0fasdfasd     
```
```
(Austrian Institute of Technology)
(https://aecid.ait.ac.at)
Version: 2.5.0fasdfasddfasfasd  
```
```
(Austrian Institute of Technology)
(https://aecid.ait.ac.at)
Version: 2.5.0fasdfasddfasfasdfdasfasdfasdfsdafasdfsdafasd
```
=> fixed indentation of version string.

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventFrequencyDetector.py
=> EFD: Fixed bug related to auto_include_flag

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventFrequencyDetector.py
=> EFD: Enabled immediate detection without training, if both limits are set

aecid-testsuite/demo/aminerJsonInputDemo/windows.yml, aecid-testsuite/runUnittests.sh, aecid-testsuite/unit/parsing/JsonModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/ParserNormalisationSchema.yml, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/ParserValidationSchema.yml, source/root/usr/lib/logdata-anomaly-miner/metadata.py
=> added nullable functionality to JsonModelElements.

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/Rules.py
=> added ValueError if type does not match in ValueMatchRule.

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventFrequencyDetector.py
=> EFD: Fixed problem that appears with empty windows

aecid-testsuite/unit/analysis/ValueRangeDetectorTest.py, aecid-testsuite/unit/data/YamlConfigTest.py, aecid-testsuite/unit/data/configfiles/multiple_components.yml, source/root/usr/lib/logdata-anomaly-miner/aminer/AminerConfig.py
Fixes Deepsource Issues
- Removed unused imports
=> Fix unused imports

.deepsource.toml, source/root/etc/aminer/conf-available/generic/AudispdParsingModel.py, source/root/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventFrequencyDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/input/JsonStateMachine.py, source/root/usr/lib/logdata-anomaly-miner/aminer/util/PersistenceUtil.py
- 1 blank line required after class docstring FLK-D204 in source/root/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py
- Missing module/function docstring PY-D0003 in source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventFrequencyDetector.py
- Inconsistent return statements PYL-R1710 in source/root/usr/lib/logdata-anomaly-miner/aminer/util/PersistenceUtil.py
- Consider removing the commented out code block PY-W0069 in source/root/usr/lib/logdata-anomaly-miner/aminer/input/JsonStateMachine.py
- Appending to dictionary immediately following its definition PY-W0072 in source/root/etc/aminer/template_config.py by excluding in .deepsource.toml
- Parameters mismatch in overridden method PYL-W0221 in source/root/etc/aminer/conf-available/generic/AudispdParsingModel.py
Fixes …
=> Fix styling issues and buggy code (DeepSource)

source/root/usr/lib/logdata-anomaly-miner/aminer/input/LogStream.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/ParserMatch.py
md5() is not used in a security related matter so the checks can be safely silenced.
Another deepsource issue is that we should conder to iterate a
dictionary directly. This issue seems to be a false positive as well and
will be silenced with this commit.
Fixes Deepsource Issues
- silencing various issues
=> Silenced various deepsource issues

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/CharsetDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EnhancedNewMatchPathValueComboDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EntropyDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventCorrelationDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventFrequencyDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventSequenceDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/MinimalTransitionTimeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/MissingMatchPathValueDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchIdValueComboDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchPathDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchPathValueComboDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchPathValueDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/PCADetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/PathArimaDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/PathValueTimeIntervalDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/TSAArimaDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/ValueRangeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableCorrelationDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py
=> added stop_learning_time and stop_learning_no_anomaly_time

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/TSAArimaDetector.py
=> TSA: Refactored import of ARIMA model and acf

Jenkinsfile, aecid-testsuite/runHowToEntropyDetector.sh, scripts/testingwrapper.sh
Fixes #1006 
- First the Wiki File needs to be updated.
- Manually tested the wiki page:
```
pwd
/tmp/entropy_test
cp /home/user/Documents/git_projects/logdata-anomaly-miner.wiki/files/* /tmp/entropy_test/
head entropy_train.log
10.35.34.242 - - [30/Sep/2021:12:52:49 +0000] "GET / HTTP/1.1" 200 6122 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0"
10.35.35.75 - - [30/Sep/2021:12:52:55 +0000] "GET / HTTP/1.1" 200 9028 "-" "WordPress/5.8.1; https://intranet.price.fox.org"
10.35.34.242 - - [30/Sep/2021:12:52:55 +0000] "GET /wp-includes/css/dist/block-library/style.min.css?ver=5.8.1 HTTP/1.1" 200 10846 "http://intranet.price.fox.org/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0"
10.35.34.242 - - [30/Sep/2021:12:52:55 +0000] …
```
=> 174 wiki howtoentropy

aecid-testsuite/runHowToMissingMatchPathValueDetector.sh, aecid-testsuite/testFunctions.sh
=> extended HowToMissingMatchPathValueDetector Tests.

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/MinimalTransitionTimeDetector.py
=> MTTD: enhanced print_persistency

source/root/usr/lib/logdata-anomaly-miner/aminer/AminerRemoteControlExecutionMethods.py, source/root/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py
Fixes #1113 
- There already was a method to close the event handler streams. However it had a bug in which the JsonConverterHandler.json_event_handlers were not processed by this method.
=> fixed bug with closing the streams.

Jenkinsfile
Fixes #
- changed the Jenkins Pipeline to skip "Branch Indexing" runs, which often fail without any reason. (probably due to them all starting at the same time - some performance issue?)
=> extended Jenkins Pipeline by skipping the branch indexing builds and returning the last build result

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/ParserCount.py
=> ParserCount: Fixed timestamp in output

aecid-testsuite/unit/analysis/MissingMatchPathValueDetectorTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/MissingMatchPathValueDetector.py
Fixes #1143 
There already exists a parameter for this "combine_values". However there still is a bug in get_channel_key where not all values are bound correctly to the path they belong to. Otherwise order of the paths in the log atom is not considered in the MissingMatchPathValueDetector.
The current implementation also does not work correctly, because only the old_last_seen_timestamp was checked instead of detector_info[0].
=> fixed the MissingMatchPathValueDetector

docs/CONFIGURATION.rst
=> Add documentation for zeromq

docs/CONFIGURATION.rst
Fixes #1163
- Corrected 3 typos in the documentation for the ZmqEventHandler.
=> Fixed 3 typos in the zmq docs

docs/conf.py
Fixes #1164
- Changed the copyright year from 2021 to 2022.
=> Changed copyright year from 2021->2022

.pre-commit-config.yaml
- Added AutoFlake8-hook to pre-commit
=> addd autoflake8 to pre-commit

.pre-commit-config.yaml, aecid-testsuite/unit/parsing/DecimalFloatValueModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/DecimalFloatValueModelElement.py
Fixes #1147 
- also added -diff to autopep8, because it was failing otherwise!
=> added check so EXP_TYPE_MANDATORY is enforced.

.pre-commit-config.yaml, aecid-testsuite/unit/parsing/DateTimeModelElementTest.py, docs/CONFIGURATION.rst, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/DateTimeModelElement.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/ModelElementInterface.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/ParserNormalisationSchema.yml, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/ParserValidationSchema.yml
fixed too broad exceptions.
Fixes #1144 
-
=> added timestamp_scale parameter to the DateTimeModelElement.

docs/CONFIGURATION.rst, source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventFrequencyDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/input/InputInterfaces.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/AnalysisNormalisationSchema.yml, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/AnalysisValidationSchema.yml
Fixes #1184
- Add unique path param to EFD
=> Add unique path param for EFD

Jenkinsfile
Fixes #
- try to stop branch indexing.
- source: https://stackoverflow.com/questions/55173365/how-to-disable-triggers-from-branch-indexing-but-still-allow-scm-triggering-in-m
=> tried to disable branch indexing.

source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py
=> fixed bug in JsonModelElement where the aminer gets stuck in an endless loop searching for \x.

aecid-testsuite/runTryItOut.sh
=> fixed TryItOut Wiki Test.

source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py
=> fixed error with string indices in YamlConfig.

aecid-testsuite/runElasticSearchWikiTest.sh
Fixes #1010 
Fixes #1118 
- Update the Wiki page with the file 
[Importing-logs-via-ElasticSearch-interface.md](https://github.com/ait-aecid/logdata-anomaly-miner/files/10521776/Importing-logs-via-ElasticSearch-interface.md)
=> Implemented ElasticSearchWikiTest.

aecid-testsuite/runUnittests.sh, aecid-testsuite/unit/data/YamlConfigTest.py, aecid-testsuite/unit/data/configfiles/granular_log_resource_list.yml, docs/CONFIGURATION.rst, source/root/usr/lib/logdata-anomaly-miner/aminer.py, source/root/usr/lib/logdata-anomaly-miner/aminer/ConfigValidator.py, source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/input/SimpleByteStreamLineAtomizerFactory.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/BaseSchema.py
No breaking changes were introduced. The old configurations still work the same.
Fixes #1155
-
=> Implemented mechanism to allow granular configuration of LogResources.

.pre-commit-config.yaml, aecid-testsuite/unit/analysis/NewMatchPathDetectorTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchPathDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/input/InputInterfaces.py, source/root/usr/lib/logdata-anomaly-miner/aminer/util/TimeTriggeredComponentInterface.py
Fixes #853 
- test1validate_parameters: test all possible parameters to initialise the detector.
- test2receive_atom:
- test if detector is learning (learn_mode=True) and stops if learn_mode=False
- test if stop_learning_time and stop_learning_no_anomaly_time are working
- test3do_timer
- test4allowlist_event
- test5persistence
- test the do_persist and load_persistence_data method
- every detector implementing persistence must use the load_persistence_data method
=> rewrote unittests for the NewMatchPathDetector

source/root/usr/lib/logdata-anomaly-miner/aminer/ConfigValidator.py
=> suppress deprecation warning for pkg_resources.

aecid-testsuite/demo/aminer/demo-config.py, aecid-testsuite/demo/aminer/demo-config.yml, source/root/usr/lib/logdata-anomaly-miner/aminer/AminerConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/events/JsonConverterHandler.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/BaseSchema.py
=> implement AminerId config property.

Jenkinsfile, scripts/testingwrapper.sh
=> HOTFIX: fix testingwrapper - development branch failing

Dockerfile, Jenkinsfile, aecid-testsuite/Dockerfile, aecid-testsuite/docker/Dockerfile_deb, aecid-testsuite/runMypy.sh, scripts/aminerwrapper.sh, scripts/distritest.sh, scripts/testingwrapper.sh, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py
Change production image to Debian Bookworm.
Please accept the aminer-ansible PR first.
Fixes #1238 
Fixes #1196 
-
=> add Debian Bookworm and Ubuntu 22.4 Tests.

Dockerfile, aecid-testsuite/Dockerfile, aecid-testsuite/runAminerXmlInputDemo.sh, aecid-testsuite/unit/analysis/PathValueTimeIntervalDetectorTest.py
=> HOTFIX: fix defusedxml installation.

Jenkinsfile, aecid-testsuite/docker/Dockerfile_fed, aecid-testsuite/docker/Dockerfile_red, scripts/distritest_red.sh
=> Fix Dockerfiles for Debian/Ubuntu.\nAdd support for Fedora and RedHat OS.

aecid-testsuite/runAminerXmlInputDemo.sh, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/CharsetDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EntropyDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventCorrelationDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventCountClusterDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventFrequencyDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventSequenceDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventTypeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/MatchValueAverageChangeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/MinimalTransitionTimeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/MissingMatchPathValueDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchIdValueComboDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchPathDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchPathValueComboDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/NewMatchPathValueDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/PCADetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/PathArimaDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/PathValueTimeIntervalDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/TSAArimaDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/ValueRangeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableCorrelationDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/VariableTypeDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/input/InputInterfaces.py
=> implement PersistableComponentInterface.

Jenkinsfile, aecid-testsuite/docker/Dockerfile_fed, scripts/distritest.sh, scripts/distritest_red.sh
Fixes #
- timeout is already done in distritest and does not need to be repeated.
=> try fixing jenkinsfile.

Jenkinsfile
Fixes #
- The docker builds for different distributions fail, because of wrong owner of the mounted volumes. This PR should fix the issue.
=> HOTFIX Jenkinsfile

Jenkinsfile, aecid-testsuite/docker/Dockerfile_deb, aecid-testsuite/docker/Dockerfile_fed, aecid-testsuite/docker/Dockerfile_red, scripts/distritest.sh
=> made cd own sh command, otherwise $PWD is not updated in the same line.

Dockerfile, Jenkinsfile, aecid-testsuite/docker/Dockerfile_deb, aecid-testsuite/unit/util/PersistenceUtilTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/util/PersistenceUtil.py
=> add some test headers for rewriting PersistenceUtilTest.

docs/CONFIGURATION.rst
=> 233 fix PCADetector Documentation.

Jenkinsfile, README.md, scripts/aminer_install.sh
=> 234 improve README and aminer_install to work with all supported OSes.

Jenkinsfile
Fixes #1140
- This does not improve on the build time of docker containers, but it might be much faster in total time needed to run all of the tests.
=> update Jenkinsfile to run all tests in parallel.

aecid-testsuite/demo/aminer/demo-config.py, aecid-testsuite/demo/aminerJsonInputDemo/aminerJsonInputDemo.sh, aecid-testsuite/demo/aminerRemoteControl/demo-config.py, aecid-testsuite/integration/aminerIntegrationTest.sh, aecid-testsuite/integration/aminerIntegrationTest2.sh, aecid-testsuite/integration/config.py, aecid-testsuite/integration/config21.py, aecid-testsuite/integration/config22.py, aecid-testsuite/integration/declarations.sh, aecid-testsuite/runRemoteControlTest.sh, aecid-testsuite/runSuspendModeTest.sh, aecid-testsuite/testFunctions.sh, aecid-testsuite/unit/events/KafkaEventHandlerTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer.py
=> make jenkins tests independent from computing capacities.

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/CharsetDetector.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EntropyDetector.py
=> 236 charset detector fix integer handling

aecid-testsuite/integration/declarations.sh, aecid-testsuite/unit/events/KafkaEventHandlerTest.py
Fixes #
- fix kafka errors in unittests
=> increase kafka timeout.

aecid-testsuite/demo/ait-lds2-russellmitchell-config.yml
=> Create Russellmitchell reference configuration

aecid-testsuite/demo/aminer/demo-config.py, aecid-testsuite/demo/aminer/demo-config.yml, docs/CONFIGURATION.rst, source/root/usr/lib/logdata-anomaly-miner/aminer/YamlConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/DateTimeModelElement.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/normalisation/ParserNormalisationSchema.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/validation/ParserValidationSchema.py
=> 241 dtme timestamps

source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/PCADetector.py
Fixes #1291
- Fix feature list in PCA detector
=> Fix feature list order in PCA detector

aecid-testsuite/unit/util/JsonUtilTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/util/JsonUtil.py
=> rewrite unittests for JsonUtil.

aecid-testsuite/unit/TestBase.py, aecid-testsuite/unit/data/parallel_configs/analysis_config.py, aecid-testsuite/unit/data/parallel_configs/events_config.py, aecid-testsuite/unit/data/parallel_configs/input_config.py, aecid-testsuite/unit/data/parallel_configs/parsing_config.py, aecid-testsuite/unit/data/parallel_configs/util_config.py, aecid-testsuite/unit/util/SecureOSFunctionsTest.py, aecid-testsuite/unit/util/clientTest4.py, aecid-testsuite/unit/util/clientTest6.py, source/root/usr/lib/logdata-anomaly-miner/aminer/AnalysisChild.py, source/root/usr/lib/logdata-anomaly-miner/aminer/util/SecureOSFunctions.py
=> rewrite unittests for SecureOSFunctions.

aecid-testsuite/unit/analysis/EventFrequencyDetectorTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/analysis/EventFrequencyDetector.py
Fixes #1312
- Fix time index persistence in EFD
=> Fix time index persistence in EFD

aecid-testsuite/unit/parsing/JsonModelElementTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/parsing/JsonModelElement.py
=> fix newline parsing in json string values.

source/root/usr/lib/logdata-anomaly-miner/aminer/input/ByteStreamLineAtomizer.py
=> extend missing timestamp warning in ByteStreamLineAtomizer.

aecid-testsuite/unit/data/YamlConfigTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/AminerConfig.py, source/root/usr/lib/logdata-anomaly-miner/aminer/events/JsonConverterHandler.py, source/root/usr/lib/logdata-anomaly-miner/aminer/input/LogAtom.py, source/root/usr/lib/logdata-anomaly-miner/aminer/schemas/BaseSchema.py
Fixes #1334 
- added a log line identifier in the json output
- introduced a parameter in the AMiner config to turn log line identifier on/off
=> Add an optional log line identifier to json output

source/root/usr/lib/logdata-anomaly-miner/aminer.py
=> Improve LogResourceList error message when url does not start with file:// or unix://.

aecid-testsuite/unit/events/DefaultMailNotificationEventHandlerTest.py, source/root/usr/lib/logdata-anomaly-miner/aminer/events/DefaultMailNotificationEventHandler.py
=> rewrite unittests for DefaultMailNotificationEventHandler.

Jenkinsfile
=> add test in jenkinsfile for Ubuntu 24.04.

scripts/aminerwrapper.sh, source/root/usr/lib/logdata-anomaly-miner/aminer/util/SecureOSFunctions.py
Hotfix for failing flake tests in CI pipeline.
-
=> remove global variables from SecureOSFunctions.
